name: slither_game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.17.0
  web_socket_channel: ^3.0.0
  uuid: ^4.0.0
  supabase_flutter: ^2.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flame_lint: ^1.4.1

flutter:
  uses-material-design: true
