name: slither_server
description: Servidor WebSocket para Slither Game multijugador
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.4
  uuid: ^4.0.0
  web_socket_channel: ^2.4.0
